package edu.uclm.esi.fakeaccountsbe.tests;// Generated by Selenium IDE

import static org.junit.jupiter.api.Assertions.assertEquals;

import java.time.Duration;
import java.util.HashMap;
import java.util.Map;

import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.openqa.selenium.By;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.chrome.ChromeOptions;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;

public class TestBuscarRectorTest {
	private WebDriver driver;
	private Map<String, Object> vars;
	JavascriptExecutor js;

	@BeforeEach
	public void setUp() {
		System.setProperty("webdriver.chrome.driver", "C:/Users/Msi/Downloads/chromedriver-win64/chromedriver-win64/chromedriver.exe");
		ChromeOptions options = new ChromeOptions();
		options.setBinary("C:/Users/Msi/Downloads/chrome-win64/chrome-win64/chrome.exe");
		options.addArguments("--remote-allow-origins=*");
		options.addArguments("--no-sandbox");
		options.addArguments("--disable-dev-shm-usage");
		driver = new ChromeDriver(options);
		js = (JavascriptExecutor) driver;
		vars = new HashMap<String, Object>();
	}

	@AfterEach
	public void tearDown() {
		driver.quit();
	}

	@Test
	public void testBuscarAlRector() {
	    WebDriverWait wait = new WebDriverWait(driver, Duration.ofSeconds(10));

	    driver.get("https://directorio.uclm.es/");
	    this.pausa(1000);
	    driver.manage().window().setSize(new Dimension(1241, 992));
	    WebElement caja = driver.findElement(By.id("CPH_CajaCentro_tb_busqueda"));
	    
	    this.js.executeScript("arguments[0].scrollIntoView(true); arguments[0].focus", caja);
	    
	    driver.findElement(By.id("CPH_CajaCentro_tb_busqueda")).click();
	    driver.findElement(By.id("CPH_CajaCentro_tb_busqueda")).sendKeys("Julián Garde");
	    driver.findElement(By.cssSelector(".hidden-xs")).click();

	    wait.until(ExpectedConditions.visibilityOfElementLocated(By.id("CPH_CajaCentro_gv_personas_lkbtn_descripcionPersona_0"))).click();

	    String cargoText = wait.until(ExpectedConditions.visibilityOfElementLocated(By.id("CPH_CajaCentro_rpt_cargos_lb_cargo_0"))).getText();
	    assertEquals("RECTOR/A", cargoText);
	}
	
	private void pausa(int tiempo) {
	try

	{
		Thread.sleep(tiempo);
	}catch(
	InterruptedException e)
	{
		e.printStackTrace();
	}
	}
}
